# Generated by Django 3.1.7 on 2021-02-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulos',
            name='seccion',
            field=models.CharField(default='seccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='nombre',
            field=models.CharField(default='articulo', max_length=30),
        ),
    ]
