# Generated by Django 3.1.7 on 2021-07-13 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_preguntas', '0003_remove_pregunta_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_preguntas.tema'),
        ),
    ]
