# Generated by Django 3.1.7 on 2021-07-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_preguntas', '0004_pregunta_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
